import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "../styles/Home.module.css";
import { GraphQLClient, gql } from "graphql-request";
import BlogCard from "../components/BlogCard";
import Loader from "../components/Loader";

const inter = Inter({ subsets: ["latin"] });

const query = gql`
  {
    posts {
      datePublished
      id
      slug
      title
      content {
        html
      }
      coverPhoto {
        url
      }
      author {
        name
        avatar {
          url
        }
      }
    }
  }
`;

const hygraph = new GraphQLClient(
  "https://eu-central-1-shared-euc1-02.cdn.hygraph.com/content/cln82njelfxmj01uobkoa82a2/master"
);

export async function getStaticProps() {
  const { posts } = await hygraph.request(query);

  return {
    props: {
      posts,
    },
    // revalidate: 10,
  };
}

export default function Home({ posts }) {
  console.log(posts);
  if (!posts) {
    return <Loader />;
  }

  return (
    <>
      <Head>
        <title>Bloggy Nextjs GraphQL App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header>
        <h1 className={styles.header}>Blog</h1>
      </header>
      <main className={`${styles.main}`}>
        <BlogCard />
        {posts?.map(
          ({ id, title, author, coverPhoto, content, datePublished, slug }) => {
            return (
              <BlogCard
                key={id}
                title={title}
                authorName={author.name}
                authorImg={author.avatar?.url}
                coverPhoto={coverPhoto.url}
                content={content.html}
                datePublished={datePublished}
                slug={slug}
              />
            );
          }
        )}
      </main>
    </>
  );
}
